// src/components/SEO/SEO.jsx
import React from 'react'
import { Helmet } from 'react-helmet'
import PropTypes from 'prop-types'
import { useStaticQuery, graphql } from 'gatsby'
import Facebook from './Facebook'
import Twitter from './Twitter'

// Complete tutorial: https://www.gatsbyjs.org/docs/add-seo-component/

const SEO = ({ title, desc, banner, pathname, article, node }) => {
  const { site } = useStaticQuery(query)

  const {
    buildTime,
    siteMetadata: {
      siteUrl,
      defaultTitle,
      defaultDescription,
      defaultBanner,
      headline,
      siteLanguage,
      ogLanguage,
      author,
      twitter,
      facebook,
    },
  } = site

  const seo = {
    title: title || defaultTitle,
    description: desc || defaultDescription,
    image: `${siteUrl}${banner || defaultBanner}`,
    url: `${siteUrl}${pathname || ''}`,
  }

  // schema.org in JSONLD format
  // https://developers.google.com/search/docs/guides/intro-structured-data
  // You can fill out the 'author', 'creator' with more data or another type (e.g. 'Organization')

  const schemaOrgWebPage = {
    '@context': 'http://schema.org',
    '@type': 'WebPage',
    url: siteUrl,
    headline,
    inLanguage: siteLanguage,
    mainEntityOfPage: siteUrl,
    description: defaultDescription,
    name: defaultTitle,
    author: {
      '@type': 'Person',
      name: author,
    },
    copyrightHolder: {
      '@type': 'Person',
      name: author,
    },
    copyrightYear: '2022',
    creator: {
      '@type': 'Person',
      name: author,
    },
    publisher: {
      '@type': 'Person',
      name: author,
    },
    datePublished: '2022-01-21T10:30:00+01:00',
    dateModified: buildTime,
    image: {
      '@type': 'ImageObject',
      url: `${siteUrl}${defaultBanner}`,
    },
    contactPoint: {
      '@type': 'ContactPoint',
      email: 'enquiries@jamesshopland.com',
      contactType: 'Owner',
      image: {
        '@type': 'ImageObject',
        url: seo.image,
      },
    },
  }

  // Initial breadcrumb list

  const itemListElement = [
    {
      '@type': 'ListItem',
      item: {
        '@id': siteUrl,
        name: 'Homepage',
      },
      position: 1,
    },
  ]

  let schemaArticle = null

  if (article) {
    schemaArticle = {
      '@context': 'http://schema.org',
      '@type': 'Article',
      author: {
        '@type': 'Person',
        name: author,
      },
      copyrightHolder: {
        '@type': 'Person',
        name: author,
      },
      copyrightYear: '2019',
      creator: {
        '@type': 'Person',
        name: author,
      },
      publisher: {
        '@type': 'Organization',
        name: author,
        logo: {
          '@type': 'ImageObject',
          url: `${siteUrl}${defaultBanner}`,
        },
      },
      datePublished: node.first_publication_date,
      dateModified: node.last_publication_date,
      description: seo.description,
      headline: seo.title,
      inLanguage: siteLanguage,
      url: seo.url,
      name: seo.title,
      image: {
        '@type': 'ImageObject',
        url: seo.image,
      },
      mainEntityOfPage: seo.url,
    }
    // Push current blogpost into breadcrumb list
    itemListElement.push({
      '@type': 'ListItem',
      item: {
        '@id': seo.url,
        name: seo.title,
      },
      position: 2,
    })
  }

  const breadcrumb = {
    '@context': 'http://schema.org',
    '@type': 'BreadcrumbList',
    description: 'Breadcrumbs list',
    name: 'Breadcrumbs',
    itemListElement,
  }

  return (
    <>
      <Helmet title={seo.title}>
        <html lang={siteLanguage} />
        <meta name="description" content={seo.description} />
        <meta name="image" content={seo.image} />
        <meta name="gatsby-starter" content="Gatsby Starter Prismic" />
        {/* Insert schema.org data conditionally (webpage/article) + everytime (breadcrumbs) */}
        {!article && (
          <script type="application/ld+json">
            {JSON.stringify(schemaOrgWebPage)}
          </script>
        )}
        {article && (
          <script type="application/ld+json">
            {JSON.stringify(schemaArticle)}
          </script>
        )}
        <script type="application/ld+json">{JSON.stringify(breadcrumb)}</script>
      </Helmet>
      <Facebook
        desc={seo.description}
        image={seo.image}
        title={seo.title}
        type={article ? 'article' : 'website'}
        url={seo.url}
        locale={ogLanguage}
        name={facebook}
      />
      <Twitter
        title={seo.title}
        image={seo.image}
        desc={seo.description}
        username={twitter}
      />
    </>
  )
}

export default SEO

SEO.propTypes = {
  title: PropTypes.string,
  desc: PropTypes.string,
  banner: PropTypes.string,
  pathname: PropTypes.string,
  article: PropTypes.bool,
  node: PropTypes.object,
}

SEO.defaultProps = {
  title: null,
  desc: null,
  banner: null,
  pathname: null,
  article: false,
  node: null,
}

const query = graphql`
  query SEO {
    site {
      buildTime(formatString: "YYYY-MM-DD")
      siteMetadata {
        siteUrl
        defaultTitle: title
        defaultDescription: description
        defaultBanner: banner
        headline
        siteLanguage
        ogLanguage
        author
        twitter
        facebook
      }
    }
  }
`

// src/components/Seo.svelte
<svelte:head>
	<meta charset="utf-8" />
	<meta httpEquiv="x-ua-compatible" content="ie=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="theme-color" content="#171731" />
	<meta
		name="twitter:image:alt"
		content="James Shopland, Web Developer. Personal site to test web design frameworks and software development skills."
	/>
	<meta name="twitter:image" content="https://jamesshopland.com/icons/icon-512x512.png" />
	<meta
		name="twitter:description"
		content="James Shopland, Web Developer. Personal site to test web design frameworks and software development skills."
	/>
	<meta name="twitter:title" content="James Shopland" />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:creator" content="@JollyShopland" />
	<meta
		property="og:image:alt"
		content="James Shopland, Web Developer. Personal site to test web design frameworks and software development skills."
	/>
	<meta property="og:image" content="https://jamesshopland.com/icons/icon-512x512.png" />
	<meta
		property="og:description"
		content="James Shopland, Web Developer. Personal site to test web design frameworks and software development skills."
	/>
	<meta property="og:title" content="James Shopland" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://jamesshopland.com" />
	<meta property="og:locale" content="en_GB" />
	<meta name="gatsby-starter" content="Gatsby Starter Prismic" />
	<meta name="image" content="https://jamesshopland.com/icons/icon-512x512.png" />
	<meta
		name="description"
		content="James Shopland, Web Developer. Personal site to test web design frameworks and software development skills."
	/>
	<link rel="sitemap" type="application/xml" href="/sitemap/sitemap-index.xml" />
	<title>James Shopland</title>
	<script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "WebPage",
        "url": "https://jamesshopland.com",
        "headline": "James Shopland Personal Site",
        "inLanguage": "en",
        "mainEntityOfPage": "https://jamesshopland.com",
        "description": "James Shopland, Web Developer. Personal site to test web design frameworks and software development skills.",
        "name": "James Shopland",
        "author": { "@type": "Person", "name": "James Shopland" },
        "copyrightHolder": { "@type": "Person", "name": "James Shopland" },
        "copyrightYear": "2022",
        "creator": { "@type": "Person", "name": "James Shopland" },
        "publisher": { "@type": "Person", "name": "James Shopland" },
        "datePublished": "2022-01-21T10:30:00+01:00",
        "dateModified": "2022-08-10",
        "image": {
          "@type": "ImageObject",
          "url": "https://jamesshopland.com/icons/icon-512x512.png"
        },
        "contactPoint": {
          "@type": "ContactPoint",
          "email": "enquiries@jamesshopland.com",
          "contactType": "Owner",
          "image": {
            "@type": "ImageObject",
            "url": "https://jamesshopland.com/icons/icon-512x512.png"
          }
        }
      }
	</script>
	<script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "BreadcrumbList",
        "description": "Breadcrumbs list",
        "name": "Breadcrumbs",
        "itemListElement": [
          {
            "@type": "ListItem",
            "item": { "@id": "https://jamesshopland.com", "name": "Homepage" },
            "position": 1
          }
        ]
      }
	</script>
	<link rel="icon" href="/favicon-32x32.png?v=26c391d67d44c6f3d5aa0f325fca85de" type="image/png" />
	<link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymous" />
	<link
		rel="apple-touch-icon"
		sizes="48x48"
		href="/icons/icon-48x48.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
	<link
		rel="apple-touch-icon"
		sizes="72x72"
		href="/icons/icon-72x72.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
	<link
		rel="apple-touch-icon"
		sizes="96x96"
		href="/icons/icon-96x96.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
	<link
		rel="apple-touch-icon"
		sizes="144x144"
		href="/icons/icon-144x144.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
	<link
		rel="apple-touch-icon"
		sizes="192x192"
		href="/icons/icon-192x192.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
	<link
		rel="apple-touch-icon"
		sizes="256x256"
		href="/icons/icon-256x256.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
	<link
		rel="apple-touch-icon"
		sizes="384x384"
		href="/icons/icon-384x384.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
	<link
		rel="apple-touch-icon"
		sizes="512x512"
		href="/icons/icon-512x512.png?v=26c391d67d44c6f3d5aa0f325fca85de"
	/>
</svelte:head>
